// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetToken() {
  return window['go']['main']['App']['GetToken']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetToken(arg1) {
  return window['go']['main']['App']['SetToken'](arg1);
}

export function StartTunnel(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTunnel'](arg1, arg2, arg3);
}

export function StopTunnel() {
  return window['go']['main']['App']['StopTunnel']();
}
