// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetToken():Promise<string>;

export function Quit():Promise<void>;

export function SetToken(arg1:string):Promise<void>;

export function StartTunnel(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StopTunnel():Promise<void>;
